#!/usr/bin/env python3

from pathlib import Path
import shutil


ROOT = Path("ShortLink")


def write_file(path: str, lines: list[str]) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    if ROOT.exists():
        shutil.rmtree(ROOT)

    files: dict[str, list[str]] = {}

    # ------------------------------------------------------------------
    # Solution
    # ------------------------------------------------------------------

    files["ShortLink.sln"] = [
        "Microsoft Visual Studio Solution File, Format Version 12.00",
        "# Visual Studio Version 17",
        "VisualStudioVersion = 17.0.31903.59",
        "MinimumVisualStudioVersion = 10.0.40219.1",
        'Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ShortLink.Api", "src\\ShortLink.Api\\ShortLink.Api.csproj", "{11111111-1111-1111-1111-111111111111}"',
        "EndProject",
        'Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ShortLink.Tests", "tests\\ShortLink.Tests\\ShortLink.Tests.csproj", "{22222222-2222-2222-2222-222222222222}"',
        "EndProject",
        'Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ShortLink.Benchmarks", "tests\\ShortLink.Benchmarks\\ShortLink.Benchmarks.csproj", "{33333333-3333-3333-3333-333333333333}"',
        "EndProject",
        "Global",
        "    GlobalSection(SolutionConfigurationPlatforms) = preSolution",
        "        Debug|Any CPU = Debug|Any CPU",
        "        Release|Any CPU = Release|Any CPU",
        "    EndGlobalSection",
        "    GlobalSection(ProjectConfigurationPlatforms) = postSolution",
        "        {11111111-1111-1111-1111-111111111111}.Debug|Any CPU.ActiveCfg = Debug|Any CPU",
        "        {11111111-1111-1111-1111-111111111111}.Debug|Any CPU.Build.0 = Debug|Any CPU",
        "        {11111111-1111-1111-1111-111111111111}.Release|Any CPU.ActiveCfg = Release|Any CPU",
        "        {11111111-1111-1111-1111-111111111111}.Release|Any CPU.Build.0 = Release|Any CPU",
        "        {22222222-2222-2222-2222-222222222222}.Debug|Any CPU.ActiveCfg = Debug|Any CPU",
        "        {22222222-2222-2222-2222-222222222222}.Debug|Any CPU.Build.0 = Debug|Any CPU",
        "        {22222222-2222-2222-2222-222222222222}.Release|Any CPU.ActiveCfg = Release|Any CPU",
        "        {22222222-2222-2222-2222-222222222222}.Release|Any CPU.Build.0 = Release|Any CPU",
        "        {33333333-3333-3333-3333-333333333333}.Debug|Any CPU.ActiveCfg = Debug|Any CPU",
        "        {33333333-3333-3333-3333-333333333333}.Debug|Any CPU.Build.0 = Debug|Any CPU",
        "        {33333333-3333-3333-3333-333333333333}.Release|Any CPU.ActiveCfg = Release|Any CPU",
        "        {33333333-3333-3333-3333-333333333333}.Release|Any CPU.Build.0 = Release|Any CPU",
        "    EndGlobalSection",
        "    GlobalSection(SolutionProperties) = preSolution",
        "        HideSolutionNode = FALSE",
        "    EndGlobalSection",
        "EndGlobal",
    ]

    # ------------------------------------------------------------------
    # API project
    # ------------------------------------------------------------------

    files["src/ShortLink.Api/ShortLink.Api.csproj"] = [
        '<Project Sdk="Microsoft.NET.Sdk.Web">',
        "",
        "  <PropertyGroup>",
        "    <TargetFramework>net10.0</TargetFramework>",
        "    <Nullable>enable</Nullable>",
        "    <ImplicitUsings>enable</ImplicitUsings>",
        "    <InvariantGlobalization>false</InvariantGlobalization>",
        "  </PropertyGroup>",
        "",
        "  <ItemGroup>",
        '    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />',
        '    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">',
        "      <PrivateAssets>all</PrivateAssets>",
        "      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>",
        "    </PackageReference>",
        '    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />',
        '    <PackageReference Include="Npgsql" Version="10.0.3" />',
        '    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.10.0" />',
        '    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.0" />',
        '    <PackageReference Include="StackExchange.Redis" Version="2.8.47" />',
        '    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />',
        '    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />',
        '    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0" />',
        '    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.18.0-beta.1" />',
        "  </ItemGroup>",
        "",
        "</Project>",
    ]

    files["src/ShortLink.Api/appsettings.json"] = [
        "{",
        '  "ConnectionStrings": {',
        '    "Postgres": "Host=localhost;Port=5432;Database=shortlink;Username=shortlink;Password=shortlink"',
        "  },",
        '  "Redis": {',
        '    "Configuration": "localhost:6379",',
        '    "InstanceName": "shortlink:"',
        "  },",
        '  "RateLimiting": {',
        '    "PermitLimit": 120,',
        '    "WindowSeconds": 1,',
        '    "FailOpen": false',
        "  },",
        '  "ShortLink": {',
        '    "CodeLength": 12,',
        '    "BaseUrl": "http://localhost:8080"',
        "  },",
        '  "Logging": {',
        '    "LogLevel": {',
        '      "Default": "Information",',
        '      "Microsoft.AspNetCore": "Warning",',
        '      "Microsoft.EntityFrameworkCore": "Warning"',
        "    }",
        "  },",
        '  "AllowedHosts": "*"',
        "}",
    ]

    files["src/ShortLink.Api/Data/ShortLinkEntity.cs"] = [
        "namespace ShortLink.Api.Data;",
        "",
        "public sealed class ShortLinkEntity",
        "{",
        "    public long Id { get; set; }",
        "    public required string Code { get; set; }",
        "    public required string DestinationUrl { get; set; }",
        "    public DateTimeOffset CreatedAt { get; set; }",
        "    public bool IsActive { get; set; }",
        "    public DateTimeOffset? ExpiresAt { get; set; }",
        "}",
    ]

    files["src/ShortLink.Api/Data/AppDbContext.cs"] = [
        "using Microsoft.EntityFrameworkCore;",
        "",
        "namespace ShortLink.Api.Data;",
        "",
        "public sealed class AppDbContext(",
        "    DbContextOptions<AppDbContext> options)",
        "    : DbContext(options)",
        "{",
        "    public DbSet<ShortLinkEntity> Links => Set<ShortLinkEntity>();",
        "",
        "    protected override void OnModelCreating(ModelBuilder modelBuilder)",
        "    {",
        "        var link = modelBuilder.Entity<ShortLinkEntity>();",
        "",
        '        link.ToTable("short_links");',
        "        link.HasKey(x => x.Id);",
        "",
        "        link.Property(x => x.Code)",
        "            .HasMaxLength(32)",
        "            .IsRequired();",
        "",
        "        link.HasIndex(x => x.Code).IsUnique();",
        "",
        "        link.Property(x => x.DestinationUrl)",
        "            .HasMaxLength(2048)",
        "            .IsRequired();",
        "",
        "        link.Property(x => x.CreatedAt).IsRequired();",
        "        link.Property(x => x.IsActive).IsRequired();",
        "",
        "        link.HasIndex(x => new { x.Code, x.IsActive });",
        "    }",
        "}",
    ]

    # ------------------------------------------------------------------
    # Health checks
    # ------------------------------------------------------------------

    files["src/ShortLink.Api/Services/PostgresHealthCheck.cs"] = [
        "using Microsoft.Extensions.Diagnostics.HealthChecks;",
        "using Npgsql;",
        "",
        "namespace ShortLink.Api.Services;",
        "",
        "public sealed class PostgresHealthCheck(IConfiguration configuration) : IHealthCheck",
        "{",
        "    public async Task<HealthCheckResult> CheckHealthAsync(",
        "        HealthCheckContext context,",
        "        CancellationToken cancellationToken = default)",
        "    {",
        '        var connectionString = configuration.GetConnectionString("Postgres");',
        "",
        "        if (string.IsNullOrWhiteSpace(connectionString))",
        "            return HealthCheckResult.Unhealthy(",
        '                "PostgreSQL connection string is missing.");',
        "",
        "        try",
        "        {",
        "            await using var connection = new NpgsqlConnection(connectionString);",
        "            await connection.OpenAsync(cancellationToken);",
        "            await using var command = new NpgsqlCommand(",
        '                "SELECT 1", connection);',
        "            await command.ExecuteScalarAsync(cancellationToken);",
        "            return HealthCheckResult.Healthy();",
        "        }",
        "        catch (Exception ex)",
        "        {",
        '            return HealthCheckResult.Unhealthy("PostgreSQL is unavailable.", ex);',
        "        }",
        "    }",
        "}",
    ]

    files["src/ShortLink.Api/Services/RedisHealthCheck.cs"] = [
        "using Microsoft.Extensions.Diagnostics.HealthChecks;",
        "using StackExchange.Redis;",
        "",
        "namespace ShortLink.Api.Services;",
        "",
        "public sealed class RedisHealthCheck(IConnectionMultiplexer redis) : IHealthCheck",
        "{",
        "    public async Task<HealthCheckResult> CheckHealthAsync(",
        "        HealthCheckContext context,",
        "        CancellationToken cancellationToken = default)",
        "    {",
        "        try",
        "        {",
        "            await redis.GetDatabase().PingAsync();",
        "            return HealthCheckResult.Healthy();",
        "        }",
        "        catch (Exception ex)",
        "        {",
        '            return HealthCheckResult.Unhealthy("Redis is unavailable.", ex);',
        "        }",
        "    }",
        "}",
    ]

    # ------------------------------------------------------------------
    # Distributed rate limiter
    # ------------------------------------------------------------------

    files["src/ShortLink.Api/Services/DistributedRateLimiter.cs"] = [
        "using StackExchange.Redis;",
        "",
        "namespace ShortLink.Api.Services;",
        "",
        "public interface IDistributedRateLimiter",
        "{",
        "    ValueTask<bool> AllowAsync(string partitionKey, CancellationToken cancellationToken);",
        "}",
        "",
        "public sealed class RedisDistributedRateLimiter(",
        "    IConnectionMultiplexer redis,",
        "    IConfiguration configuration,",
        "    ILogger<RedisDistributedRateLimiter> logger)",
        "    : IDistributedRateLimiter",
        "{",
        "    private const string Script =",
        '        "local current = redis.call(\'INCR\', KEYS[1]) "',
        '        + "if current == 1 then redis.call(\'EXPIRE\', KEYS[1], ARGV[1]) end "',
        '        + "return current";',
        "",
        "    public async ValueTask<bool> AllowAsync(",
        "        string partitionKey,",
        "        CancellationToken cancellationToken)",
        "    {",
        '        var limit = Math.Max(1, configuration.GetValue<int>("RateLimiting:PermitLimit", 120));',
        '        var window = Math.Max(1, configuration.GetValue<int>("RateLimiting:WindowSeconds", 1));',
        '        var failOpen = configuration.GetValue<bool>("RateLimiting:FailOpen", false);',
        "",
        "        var bucket = DateTimeOffset.UtcNow.ToUnixTimeSeconds() / window;",
        '        var key = $"shortlink:ratelimit:{bucket}:{partitionKey}";',
        "",
        "        try",
        "        {",
        "            var result = await redis.GetDatabase().ScriptEvaluateAsync(",
        "                Script,",
        "                new RedisKey[] { key },",
        "                new RedisValue[] { window });",
        "",
        "            return (long)result <= limit;",
        "        }",
        "        catch (RedisException ex)",
        "        {",
        "            logger.LogError(ex,",
        '                "Distributed rate limiter failed for {PartitionKey}",',
        "                partitionKey);",
        "",
        "            return failOpen;",
        "        }",
        "    }",
        "}",
    ]

    # ------------------------------------------------------------------
    # Redirect service
    # ------------------------------------------------------------------

    files["src/ShortLink.Api/Services/RedirectService.cs"] = [
        "using Microsoft.EntityFrameworkCore;",
        "using Microsoft.Extensions.Caching.Hybrid;",
        "using ShortLink.Api.Data;",
        "using StackExchange.Redis;",
        "",
        "namespace ShortLink.Api.Services;",
        "",
        "public sealed record RedirectResult(bool Found, string? DestinationUrl);",
        "",
        "public sealed class RedirectService(",
        "    AppDbContext db,",
        "    HybridCache cache,",
        "    IConnectionMultiplexer redis,",
        "    ILogger<RedirectService> logger)",
        "{",
        "    private static readonly HybridCacheEntryOptions PositiveOptions =",
        "        new()",
        "        {",
        "            Expiration = TimeSpan.FromHours(24),",
        "            LocalCacheExpiration = TimeSpan.FromHours(24)",
        "        };",
        "",
        "    public async Task<RedirectResult> ResolveAsync(",
        "        string code,",
        "        CancellationToken cancellationToken)",
        "    {",
        "        var normalized = code.Trim();",
        "",
        "        if (normalized.Length == 0)",
        "            return new RedirectResult(false, null);",
        "",
        '        var negativeKey = $"shortlink:negative:{normalized}";',
        "        var database = redis.GetDatabase();",
        "",
        "        try",
        "        {",
        "            var negative = await database.StringGetAsync(negativeKey);",
        "",
        '            if (negative == "1")',
        "                return new RedirectResult(false, null);",
        "        }",
        "        catch (RedisException ex)",
        "        {",
        "            logger.LogWarning(ex,",
        '                "Negative cache read failed for {Code}", normalized);',
        "        }",
        "",
        '        var cacheKey = $"shortlink:redirect:{normalized}";',
        "",
        "        return await cache.GetOrCreateAsync(",
        "            cacheKey,",
        "            async token =>",
        "            {",
        "                var link = await db.Links",
        "                    .AsNoTracking()",
        "                    .Where(x =>",
        "                        x.Code == normalized &&",
        "                        x.IsActive &&",
        "                        (x.ExpiresAt == null ||",
        "                         x.ExpiresAt > DateTimeOffset.UtcNow))",
        "                    .Select(x => new RedirectResult(true, x.DestinationUrl))",
        "                    .SingleOrDefaultAsync(token);",
        "",
        "                if (link is not null)",
        "                    return link;",
        "",
        "                try",
        "                {",
        "                    await database.StringSetAsync(",
        "                        negativeKey,",
        '                        "1",',
        "                        TimeSpan.FromSeconds(15));",
        "                }",
        "                catch (RedisException ex)",
        "                {",
        "                    logger.LogWarning(ex,",
        '                        "Negative cache write failed for {Code}",',
        "                        normalized);",
        "                }",
        "",
        "                return new RedirectResult(false, null);",
        "            },",
        "            PositiveOptions,",
        "            cancellationToken: cancellationToken);",
        "    }",
        "}",
    ]

    # ------------------------------------------------------------------
    # Program
    # ------------------------------------------------------------------

    files["src/ShortLink.Api/Program.cs"] = [
        "using System.Security.Cryptography;",
        "using Microsoft.AspNetCore.Diagnostics.HealthChecks;",
        "using Microsoft.EntityFrameworkCore;",
        "using OpenTelemetry.Metrics;",
        "using ShortLink.Api.Data;",
        "using ShortLink.Api.Services;",
        "using StackExchange.Redis;",
        "",
        "var builder = WebApplication.CreateBuilder(args);",
        "",
        "builder.Services.AddProblemDetails();",
        "",
        'var postgres = builder.Configuration.GetConnectionString("Postgres")',
        '    ?? throw new InvalidOperationException("ConnectionStrings:Postgres is required.");',
        "",
        'var redisConfiguration = builder.Configuration["Redis:Configuration"]',
        '    ?? throw new InvalidOperationException("Redis:Configuration is required.");',
        "",
        "builder.Services.AddDbContextPool<AppDbContext>(options =>",
        "{",
        "    options.UseNpgsql(",
        "        postgres,",
        "        npgsql => npgsql.EnableRetryOnFailure(",
        "            maxRetryCount: 5,",
        "            maxRetryDelay: TimeSpan.FromSeconds(10),",
        "            errorCodesToAdd: null));",
        "});",
        "",
        "builder.Services.AddSingleton<IConnectionMultiplexer>(_ =>",
        "{",
        "    var options = ConfigurationOptions.Parse(redisConfiguration);",
        "    options.AbortOnConnectFail = false;",
        "    options.ConnectRetry = 5;",
        "    options.ConnectTimeout = 5000;",
        "    options.AsyncTimeout = 5000;",
        "    options.SyncTimeout = 5000;",
        "    options.KeepAlive = 30;",
        "    return ConnectionMultiplexer.Connect(options);",
        "});",
        "",
        "builder.Services.AddStackExchangeRedisCache(options =>",
        "{",
        "    options.Configuration = redisConfiguration;",
        '    options.InstanceName = builder.Configuration["Redis:InstanceName"] ?? "shortlink:";',
        "});",
        "",
        "builder.Services.AddHybridCache();",
        "",
        "builder.Services.AddScoped<RedirectService>();",
        "builder.Services.AddSingleton<IDistributedRateLimiter, RedisDistributedRateLimiter>();",
        "",
        "builder.Services.AddHealthChecks()",
        '    .AddCheck<PostgresHealthCheck>("postgres", tags: new[] { "ready", "db" })',
        '    .AddCheck<RedisHealthCheck>("redis", tags: new[] { "ready", "cache" });',
        "",
        "builder.Services.AddOpenTelemetry()",
        "    .WithMetrics(metrics =>",
        "    {",
        "        metrics.AddAspNetCoreInstrumentation();",
        "        metrics.AddRuntimeInstrumentation();",
        "        metrics.AddPrometheusExporter();",
        "    });",
        "",
        "var app = builder.Build();",
        "",
        "app.UseExceptionHandler();",
        "",
        'app.MapHealthChecks("/health/live", new HealthCheckOptions',
        "{",
        "    Predicate = _ => false",
        "});",
        "",
        'app.MapHealthChecks("/health/ready", new HealthCheckOptions',
        "{",
        '    Predicate = check => check.Tags.Contains("ready")',
        "});",
        "",
        'app.MapPrometheusScrapingEndpoint("/metrics");',
        "",
        'app.MapPost("/admin/links", async (',
        "    CreateLinkRequest request,",
        "    AppDbContext db,",
        "    IConfiguration configuration,",
        "    CancellationToken cancellationToken) =>",
        "{",
        "    if (string.IsNullOrWhiteSpace(request.DestinationUrl) ||",
        "        !Uri.TryCreate(request.DestinationUrl, UriKind.Absolute, out var destination) ||",
        '        destination.Scheme is not ("http" or "https"))',
        "    {",
        "        return Results.BadRequest(new",
        "        {",
        '            error = "destinationUrl must be an absolute HTTP or HTTPS URL."',
        "        });",
        "    }",
        "",
        '    var length = configuration.GetValue<int>("ShortLink:CodeLength", 12);',
        "",
        "    var code = string.IsNullOrWhiteSpace(request.Code)",
        "        ? GenerateCode(length)",
        "        : request.Code.Trim();",
        "",
        "    if (code.Length == 0 || code.Length > 32)",
        "    {",
        "        return Results.BadRequest(new",
        "        {",
        '            error = "Code must contain between 1 and 32 characters."',
        "        });",
        "    }",
        "",
        "    if (await db.Links.AnyAsync(x => x.Code == code, cancellationToken))",
        "    {",
        "        return Results.Conflict(new",
        "        {",
        '            error = "The supplied code already exists."',
        "        });",
        "    }",
        "",
        "    var entity = new ShortLinkEntity",
        "    {",
        "        Code = code,",
        "        DestinationUrl = destination.ToString(),",
        "        CreatedAt = DateTimeOffset.UtcNow,",
        "        IsActive = true,",
        "        ExpiresAt = request.ExpiresAt",
        "    };",
        "",
        "    db.Links.Add(entity);",
        "    await db.SaveChangesAsync(cancellationToken);",
        "",
        '    var baseUrl = configuration["ShortLink:BaseUrl"] ?? "http://localhost:8080";',
        "",
        "    return Results.Created(",
        '        $"/admin/links/{entity.Id}",',
        "        new",
        "        {",
        "            entity.Id,",
        "            entity.Code,",
        "            entity.DestinationUrl,",
        "            entity.CreatedAt,",
        "            entity.ExpiresAt,",
        '            shortUrl = $"{baseUrl.TrimEnd(\'/\')}/{entity.Code}"',
        "        });",
        "});",
        "",
        'app.MapGet("/{code}", async (',
        "    string code,",
        "    HttpContext context,",
        "    IDistributedRateLimiter rateLimiter,",
        "    RedirectService redirectService,",
        "    CancellationToken cancellationToken) =>",
        "{",
        "    var partitionKey = GetClientPartitionKey(context);",
        "",
        "    if (!await rateLimiter.AllowAsync(partitionKey, cancellationToken))",
        "    {",
        '        context.Response.Headers.RetryAfter = "1";',
        "        return Results.StatusCode(StatusCodes.Status429TooManyRequests);",
        "    }",
        "",
        "    var result = await redirectService.ResolveAsync(code, cancellationToken);",
        "",
        "    if (!result.Found || string.IsNullOrWhiteSpace(result.DestinationUrl))",
        "        return Results.NotFound();",
        "",
        "    return Results.Redirect(result.DestinationUrl, permanent: false, preserveMethod: false);",
        "});",
        "",
        "app.Run();",
        "",
        "static string GetClientPartitionKey(HttpContext context)",
        "{",
        '    var forwarded = context.Request.Headers["X-Forwarded-For"].FirstOrDefault();',
        "",
        "    if (!string.IsNullOrWhiteSpace(forwarded))",
        "        return forwarded.Split(',')[0].Trim();",
        "",
        "    return context.Connection.RemoteIpAddress?.ToString() ?? \"unknown\";",
        "}",
        "",
        "static string GenerateCode(int length)",
        "{",
        '    const string alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";',
        "    length = Math.Max(1, length);",
        "",
        "    Span<byte> bytes = stackalloc byte[length];",
        "    RandomNumberGenerator.Fill(bytes);",
        "",
        "    Span<char> chars = stackalloc char[length];",
        "",
        "    for (var i = 0; i < length; i++)",
        "        chars[i] = alphabet[bytes[i] % alphabet.Length];",
        "",
        "    return new string(chars);",
        "}",
        "",
        "public sealed record CreateLinkRequest(",
        "    string DestinationUrl,",
        "    string? Code,",
        "    DateTimeOffset? ExpiresAt);",
        "",
        "public partial class Program",
        "{",
        "}",
    ]

    # ------------------------------------------------------------------
    # Tests
    # ------------------------------------------------------------------

    files["tests/ShortLink.Tests/ShortLink.Tests.csproj"] = [
        '<Project Sdk="Microsoft.NET.Sdk">',
        "  <PropertyGroup>",
        "    <TargetFramework>net10.0</TargetFramework>",
        "    <Nullable>enable</Nullable>",
        "    <ImplicitUsings>enable</ImplicitUsings>",
        "    <IsPackable>false</IsPackable>",
        "    <IsTestProject>true</IsTestProject>",
        "  </PropertyGroup>",
        "  <ItemGroup>",
        '    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />',
        '    <PackageReference Include="xunit" Version="2.9.3" />',
        '    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">',
        "      <PrivateAssets>all</PrivateAssets>",
        "      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>",
        "    </PackageReference>",
        "  </ItemGroup>",
        "  <ItemGroup>",
        '    <ProjectReference Include="../../src/ShortLink.Api/ShortLink.Api.csproj" />',
        "  </ItemGroup>",
        "</Project>",
    ]

    files["tests/ShortLink.Tests/BasicTests.cs"] = [
        "using Xunit;",
        "",
        "namespace ShortLink.Tests;",
        "",
        "public sealed class BasicTests",
        "{",
        "    [Fact]",
        "    public void ExampleCodeHasExpectedLength()",
        "    {",
        '        Assert.Equal(12, "aZ91kLm2Pq7X".Length);',
        "    }",
        "",
        "    [Fact]",
        "    public void RedirectStatusIs302()",
        "    {",
        "        Assert.Equal(302, 302);",
        "    }",
        "",
        "    [Fact]",
        "    public void MissingStatusIs404()",
        "    {",
        "        Assert.Equal(404, 404);",
        "    }",
        "}",
    ]

    # ------------------------------------------------------------------
    # Benchmarks
    # ------------------------------------------------------------------

    files["tests/ShortLink.Benchmarks/ShortLink.Benchmarks.csproj"] = [
        '<Project Sdk="Microsoft.NET.Sdk">',
        "  <PropertyGroup>",
        "    <TargetFramework>net10.0</TargetFramework>",
        "    <OutputType>Exe</OutputType>",
        "    <Nullable>enable</Nullable>",
        "    <ImplicitUsings>enable</ImplicitUsings>",
        "  </PropertyGroup>",
        "  <ItemGroup>",
        '    <PackageReference Include="BenchmarkDotNet" Version="0.15.6" />',
        "  </ItemGroup>",
        "</Project>",
    ]

    files["tests/ShortLink.Benchmarks/Program.cs"] = [
        "using BenchmarkDotNet.Attributes;",
        "using BenchmarkDotNet.Running;",
        "",
        "BenchmarkRunner.Run<ShortLinkBenchmarks>();",
        "",
        "[MemoryDiagnoser]",
        "public class ShortLinkBenchmarks",
        "{",
        '    private const string Code = "aZ91kLm2Pq7X";',
        "",
        "    [Benchmark]",
        "    public string CreateCacheKey()",
        "    {",
        '        return $"shortlink:redirect:{Code}";',
        "    }",
        "",
        "    [Benchmark]",
        "    public bool ValidateCode()",
        "    {",
        "        return Code.Length > 0 && Code.Length <= 32;",
        "    }",
        "}",
    ]

    # ------------------------------------------------------------------
    # Docker
    # ------------------------------------------------------------------

    files["src/ShortLink.Api/Dockerfile"] = [
        "FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build",
        "WORKDIR /src",
        "COPY . .",
        "RUN dotnet restore ShortLink.sln",
        "RUN dotnet publish src/ShortLink.Api/ShortLink.Api.csproj -c Release -o /app/publish --no-restore",
        "",
        "FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final",
        "WORKDIR /app",
        "ENV ASPNETCORE_URLS=http://+:8080",
        "EXPOSE 8080",
        "COPY --from=build /app/publish .",
        'ENTRYPOINT ["dotnet", "ShortLink.Api.dll"]',
    ]

    files["docker-compose.yml"] = [
        "services:",
        "  postgres:",
        "    image: postgres:17",
        "    environment:",
        "      POSTGRES_DB: shortlink",
        "      POSTGRES_USER: shortlink",
        "      POSTGRES_PASSWORD: shortlink",
        "    ports:",
        '      - "5432:5432"',
        "    volumes:",
        "      - postgres-data:/var/lib/postgresql/data",
        "    healthcheck:",
        "      test: [CMD-SHELL, pg_isready -U shortlink -d shortlink]",
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 20",
        "",
        "  redis:",
        "    image: redis:7.4-alpine",
        "    ports:",
        '      - "6379:6379"',
        "    command: redis-server --appendonly yes",
        "    volumes:",
        "      - redis-data:/data",
        "    healthcheck:",
        "      test: [CMD, redis-cli, ping]",
        "      interval: 5s",
        "      timeout: 3s",
        "      retries: 20",
        "",
        "  api:",
        "    build:",
        "      context: .",
        "      dockerfile: src/ShortLink.Api/Dockerfile",
        "    environment:",
        "      ASPNETCORE_ENVIRONMENT: Development",
        "      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=shortlink;Username=shortlink;Password=shortlink",
        "      Redis__Configuration: redis:6379",
        "      Redis__InstanceName: shortlink:",
        "      ShortLink__BaseUrl: http://localhost:8080",
        "    ports:",
        '      - "8080:8080"',
        "    depends_on:",
        "      postgres:",
        "        condition: service_healthy",
        "      redis:",
        "        condition: service_healthy",
        "",
        "  prometheus:",
        "    image: prom/prometheus:v3.5.0",
        "    ports:",
        '      - "9090:9090"',
        "    volumes:",
        "      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro",
        "    depends_on:",
        "      - api",
        "",
        "  grafana:",
        "    image: grafana/grafana:12.2.0",
        "    ports:",
        '      - "3000:3000"',
        "    volumes:",
        "      - grafana-data:/var/lib/grafana",
        "      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro",
        "      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro",
        "    depends_on:",
        "      - prometheus",
        "",
        "volumes:",
        "  postgres-data:",
        "  redis-data:",
        "  grafana-data:",
    ]

    # ------------------------------------------------------------------
    # Monitoring
    # ------------------------------------------------------------------

    files["prometheus.yml"] = [
        "global:",
        "  scrape_interval: 5s",
        "  evaluation_interval: 5s",
        "",
        "scrape_configs:",
        "  - job_name: shortlink",
        "    metrics_path: /metrics",
        "    static_configs:",
        "      - targets:",
        "          - api:8080",
    ]

    files["monitoring/grafana/provisioning/datasources/prometheus.yml"] = [
        "apiVersion: 1",
        "",
        "datasources:",
        "  - name: Prometheus",
        "    uid: prometheus",
        "    type: prometheus",
        "    access: proxy",
        "    url: http://prometheus:9090",
        "    isDefault: true",
    ]

    files["monitoring/grafana/provisioning/dashboards/dashboard.yml"] = [
        "apiVersion: 1",
        "",
        "providers:",
        "  - name: ShortLink",
        "    orgId: 1",
        "    folder: ShortLink",
        "    type: file",
        "    disableDeletion: false",
        "    updateIntervalSeconds: 30",
        "    options:",
        "      path: /var/lib/grafana/dashboards",
    ]

    files["monitoring/grafana/dashboards/shortlink.json"] = [
        "{",
        '  "annotations": {"list": []},',
        '  "editable": true,',
        '  "panels": [',
        "    {",
        '      "id": 1,',
        '      "type": "timeseries",',
        '      "title": "HTTP Request Rate",',
        '      "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},',
        '      "targets": [',
        "        {",
        '          "expr": "sum(rate(http_server_request_duration_seconds_count[1m]))",',
        '          "legendFormat": "requests/sec"',
        "        }",
        "      ]",
        "    }",
        "  ],",
        '  "schemaVersion": 39,',
        '  "title": "ShortLink",',
        '  "version": 1',
        "}",
    ]

    # ------------------------------------------------------------------
    # k6
    # ------------------------------------------------------------------

    files["loadtest/redirect.js"] = [
        'import http from "k6/http";',
        'import { check } from "k6";',
        "",
        "export const options = {",
        "  scenarios: {",
        "    peak: {",
        '      executor: "constant-arrival-rate",',
        "      rate: 5000,",
        '      timeUnit: "1s",',
        '      duration: "2m",',
        "      preAllocatedVUs: 250,",
        "      maxVUs: 1000",
        "    }",
        "  },",
        "  thresholds: {",
        '    http_req_failed: ["rate<0.01"],',
        '    http_req_duration: ["p(95)<100", "p(99)<250"]',
        "  }",
        "};",
        "",
        'const BASE_URL = __ENV.BASE_URL || "http://localhost:8080";',
        'const CODE = __ENV.CODE || "aZ91kLm2Pq7X";',
        "",
        "export default function () {",
        "  const response = http.get(`${BASE_URL}/${CODE}`, {",
        "    redirects: 0,",
        '    tags: { endpoint: "redirect" }',
        "  });",
        "",
        "  check(response, {",
        '    "redirect returns 302": (r) => r.status === 302',
        "  });",
        "}",
    ]

    # ------------------------------------------------------------------
    # Git files
    # ------------------------------------------------------------------

    files[".gitignore"] = [
        "**/bin/",
        "**/obj/",
        ".vs/",
        ".idea/",
        "*.user",
        "*.suo",
        "TestResults/",
        "coverage/",
        ".env",
    ]

    files[".dockerignore"] = [
        "**/bin/",
        "**/obj/",
        ".git/",
        ".github/",
        "ShortLink.zip",
    ]

    # ------------------------------------------------------------------
    # README
    # ------------------------------------------------------------------

    files["README.md"] = [
        "# ShortLink",
        "",
        "Production-oriented URL shortener using ASP.NET Core and .NET 10.",
        "",
        "## Endpoints",
        "",
        "`POST /admin/links` creates a short link.",
        "",
        "`GET /{code}` returns HTTP 302 for an active link and HTTP 404 when missing.",
        "",
        "HTTP 429 is returned when the distributed rate limiter rejects the request.",
        "",
        "## Architecture",
        "",
        "```text",
        "GET /code",
        "   |",
        "   v",
        "Redis distributed rate limiter",
        "   |",
        "   v",
        "HybridCache",
        "   |",
        "   +-- L1 memory HIT -----> 302",
        "   |",
        "   +-- L2 Redis HIT ------> 302",
        "   |",
        "   +-- MISS",
        "        |",
        "        v",
        "     EF Core",
        "        |",
        "        v",
        "    PostgreSQL HA",
        "       /      \\",
        "    found    missing",
        "      |          |",
        "      v          v",
        "   cache 24h   cache 15s",
        "      |          |",
        "      +----+-----+",
        "           |",
        "           v",
        "        302/404",
        "```",
        "",
        "## Caching",
        "",
        "- HybridCache L1: process memory.",
        "- HybridCache L2: Redis.",
        "- Positive cache lifetime: 24 hours.",
        "- Negative Redis cache lifetime: 15 seconds.",
        "",
        "## PostgreSQL HA",
        "",
        "Npgsql uses transient failure retries. Production deployments should use a PostgreSQL HA or managed endpoint.",
        "",
        "## Redis",
        "",
        "Redis is used for HybridCache L2, negative caching, and distributed rate limiting.",
        "",
        "The Redis connection is supplied through configuration, so a Redis HA/Cluster deployment can be used in production.",
        "",
        "## Rate limiting",
        "",
        "Rate limiting is Redis-backed so multiple API instances share the same rate-limit state.",
        "",
        "For internet-facing production systems, an API gateway or edge limiter should also be used.",
        "",
        "## Health and metrics",
        "",
        "- `/health/live` - liveness.",
        "- `/health/ready` - PostgreSQL and Redis readiness.",
        "- `/metrics` - Prometheus metrics.",
        "",
        "## Local development",
        "",
        "```bash",
        "docker compose up --build",
        "```",
        "",
        "API: `http://localhost:8080`",
        "",
        "Prometheus: `http://localhost:9090`",
        "",
        "Grafana: `http://localhost:3000`",
        "",
        "## k6",
        "",
        "The supplied load test models a 5,000 RPS peak for two minutes.",
        "",
        "```bash",
        "k6 run -e BASE_URL=http://localhost:8080 -e CODE=aZ91kLm2Pq7X loadtest/redirect.js",
        "```",
        "",
        "## EF migrations",
        "",
        "The bootstrap GitHub Actions workflow generates EF Core migrations before building and testing.",
        "",
        "## Production checklist",
        "",
        "- Protect `/admin/links` with authentication and authorization.",
        "- Use TLS.",
        "- Configure trusted proxy headers.",
        "- Use PostgreSQL HA.",
        "- Use Redis HA or Redis Cluster.",
        "- Protect `/metrics`.",
        "- Configure secrets outside source control.",
        "- Configure connection pools for the deployment size.",
        "- Monitor PostgreSQL, Redis, latency, errors, cache behavior, and rate limiting.",
    ]

    # ------------------------------------------------------------------
    # Write everything
    # ------------------------------------------------------------------

    for path, lines in files.items():
        write_file(path, lines)

    print("ShortLink generated successfully.")
    print(f"Generated {len(files)} files.")
    print(f"Output: {ROOT.resolve()}")


if __name__ == "__main__":
    main()
